### ISSUE TITLE
Seurat objects PDAC data

### ISSUE THREAD

**Issue by browaeysrobin** [MarcElosua/SPOTlight_deconvolution_analysis#2]
Hi @MarcElosua,

Thank you for the SPOTlight package and this code here to reproduce the results of your paper. I am just wondering whether you are planning to make a public repository (e.g. on zenodo) where you will put the Seurat objects of the processed spatial data (or the spatial data you load in your 'pancreas_PDAC/0-inDrop_itai_annotation.Rmd' script). I started looking at the PDAC data downloaded from GEO myself but it seems to take some time and work to convert it to the right format to run the analyses you show here. Therefore I thought I could just ask whether it would be possible to share the PDAC Seurat objects after processing (or the direct and concrete input data of that script) .

Thank you in advance!

**Comment by MarcElosua** [comment]
Hi @browaeysrobin, 
As you mention the data we use here is public and it comes from Reuben Moncada's [paper](https://pubmed.ncbi.nlm.nih.gov/31932730/) from Itai Yanai's lab **Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas**. The GEO reference, just to confirm we're looking at the same one, is GSE111672. Since the data is already public we are not planning on making the processed Seurat objects available.

I am more than happy to share the processed Spatial and Single Cell data so you don't have to do the cumbersome process all over again! I see you have this email robin.browaeys@ugent.be in your profile, let me know if sending the files there works for you or if there is an alternative option you prefer. Feel free to email me directly at marc.elosua@cnag.crg.eu.
